apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: kiosk-example
spec:
    replicas: 1
    selector:
        matchLabels:
            tier: fronted
            version: "3"
    minReadySeconds: 5
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                tier: fronted
                version: "3"
            annotations:
                maintainer: miguel
        spec:
            containers:
            - name: kiosk-example
              image: devopswkubernetes/kiosk-example
              ports:
              - containerPort: 5000
              env:
              - name: REDIS_HOST
                value: lcredis-service
