apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: lmysql
spec:
    replicas: 1
    selector:
        matchLabels:
            tier: database
            version: "5.7"
    template:
        metadata:
            labels:
                tier: database
                version: "5.7"
        spec:
            containers:
            - name: lmysql
              image: mysql:5.7
              ports:
              - containerPort: 3306
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: mysql-root
                          key: password
                - name: MYSQL_DATABASE
                  valueFrom:
                      configMapKeyRef:
                          name: mysql-config
                          key: database
                - name: MYSQL_USER
                  valueFrom:
                      configMapKeyRef:
                          name: mysql-config
                          key: user
                - name: MYSQL_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: mysql-user
                          key: password
