apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: lcredis
spec:
    replicas: 1
    selector:
        matchLabels:
            tier: cache
            version: "3.0"
    minReadySeconds: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                tier: cache
                version: "3.0"
        spec:
            containers:
            - name: lcredis
              image: redis:3.0
              ports:
              - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: lcredis-service
spec:
    selector:
        tier: cache
    ports:
    - name: tcp6379
      port: 6379
      targetPort: 6379
      protocol: TCP
