apiVersion: v1
kind: Secret
metadata:
    name: mysql-user
type: Opaque
data:
    password: cGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
    name: mysql-root
type: Opaque
data:
    password: bXlzcWxwYXNz
