apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: boomload-deploy
    namespace: test
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: loadgenerator-deploy
        spec:
            containers:
            - name: boom-deploy
              image: williamyeh/boom
              command: ["/bin/sh","-c"]
              args: ["while true ; do boom http://node-js-deploy/ -c 10 -n 100 ; sleep 1 ; done"]
