apiVersion: v1
kind: Pod
metadata:
    name: hello-nodejs
    labels:
        app: hello-nodejs
spec:
    containers:
    - name: nodejs-port
      image: miguelgt/k8s-demo
      ports:
      - containerPort: 3000
