apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hello-nodejs-deploy
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: hello-nodejs
        spec:
            containers:
            - name: k8s-demo
              image: miguelgt/k8s-demo
              ports:
              - containerPort: 3000
