apiVersion: v1
kind: Service
metadata:
    name: hello-nodejs-svc
    labels:
        app: hello-nodejs
spec:
    type: NodePort
    selector:
        app: hello-nodejs
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
