apiVersion: v1
kind: ReplicationController
metadata:
    name: hello-nodejs-rc
spec:
    replicas: 3
    selector:
        app: hello-nodejs
    template:
        metadata:
            labels:
                app: hello-nodejs
        spec:
            containers:
            - name: k8s-demo
              image: miguelgt/k8s-demo
              ports:
              - containerPort: 3000

