apiVersion: v1
kind: Service
metadata:
    name: nodejs-multi-svc
    labels:
        app: nodejs-multi
spec:
    type: LoadBalancer
    selector:
        app: nodejs-multi
    ports:
    - name: http
      protocol: TCP
      port: 80
    - name: fake-admin-http
      protocol: TCP
      port: 8888

