apiVersion: v1
kind: ReplicationController
metadata:
    name: nodejs-multi-ctl
    labels:
        app: nodejs-multi
spec:
    replicas: 3
    selector:
        app: nodejs-multi
    template:
        metadata:
            labels:
                app: nodejs-multi
        spec:
            containers:
            - name: nodejs-multi
              image: jonbaier/node-express-multi:latest
              ports:
              - containerPort: 80
              - containerPort: 8888
