apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dictonary-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dictonary
  template:
    metadata:
      labels:
        app: dictonary
    spec:
      containers:
      - name: server
        image: brendanburns/dictionary-server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
