apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: hello-nodejs
        spec:
            containers:
            - name: hello-nodejs
              image: miguelgt/k8s-demo:v2
              ports:
              - containerPort: 3000
              volumeMounts:
              - name: cred-volume
                mountPath: /etc/creds
                readOnly: true
            volumes:
            - name: cred-volume
              secret:
                  secretName: db-secrets

