apiVersion: v1
kind: Service
metadata:
    name: node-js-scale-ab
    namespace: test
    labels:
        service: node-js-scale-ab
spec:
    type: LoadBalancer
    selector:
        service: node-js-scale-ab
    ports:
    - port: 80
    sessionAffinity: ClientIP
