apiVersion: v1
kind: ReplicationController
metadata:
    name: bash-loop-rc
spec:
    replicas: 3
    template:
        metadata:
            labels:
                name: bash-loop-rc
        spec:
            containers:
            - name: bash-loop
              image: ubuntu
              command: ["/bin/bash", "-c", "while true; do sleep 10; done"]
