apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx
spec:
    replicas: 3
    template:
        metadata:
            labels:
                run: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: nginx
    namespace: default
spec:
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 90
    scaleTargetRef:
        apiVersion: v1
        kind: ReplicationController
        name: nginx
