apiVersion: v1
kind: Service
metadata:
    name: http-pd
    namespace: test
    labels:
        name: http-pd
spec:
    type: LoadBalancer
    selector:
        name: http-pd
    ports:
    - name: http
      port: 80
      protocol: TCP
