apiVersion: v1
kind: ReplicationController
metadata:
    name: http-pd
    namespace: test
    labels:
        name: http-pd
spec:
    replicas: 3
    selector:
        name: http-pd
    template:
        metadata:
            name: http-pd
            labels:
                name: http-pd
        spec:
            containers:
            - name: http-pd
              image: nginx:latest
              ports:
              - containerPort: 80
              volumeMounts:
              - name: gce-pd
                mountPath: /usr/share/nginx/html
            volumes:
            - name: gce-pd
              gcePersistentDisk:
                  pdName: mysite-volume-1
                  fsType: ext4
                  readOnly: true
