apiVersion: v1
kind: Pod
metadata:
    name: memory-pod
    namespace: test
spec:
    containers:
    - name: memory-pod
      image: nginx:latest
      ports:
      - containerPort: 80
      volumeMounts:
      - name: memory-volume
        mountPath: /memory-pd
    volumes:
    - name: memory-volume
      emptyDir:
          medium: Memory
