apiVersion: v1
kind: Pod
metadata:
    name: guaranteed
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
          requests:
              cpu: 0.3
              memory: 350Mi
          limits:
              cpu: 0.3
              memory: 350Mi
