apiVersion: v1
kind: Service
metadata:
    name: helloworld-service
spec:
    type: LoadBalancer
    selector:
        app: helloworld-db
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
