apiVersion: v1
kind: ReplicationController
metadata:
    name: node-js-scale
    namespace: test
    labels:
        app: node-js-scale
spec:
    replicas: 1
    selector:
        app: node-js-scale
    template:
        metadata:
            labels:
                app: node-js-scale
        spec:
            containers:
            - name: node-js-scale
              image: jonbaier/pod-scaling:0.1
              ports:
              - containerPort: 80
