apiVersion: v1
kind: Service
metadata:
    name: node-js-scale
    namespace: test
    labels:
        app: node-js-scale
spec:
    type: LoadBalancer
    sessionAffinity: ClientIP
    selector:
        app: node-js-scale
    ports:
    - port: 80
