apiVersion: v1
kind: Pod
metadata:
    name: secret-access
spec:
    containers:
    - name: centos
      image: centos
      command: ["/bin/sh", "-c", "while true; do cat /secret/password; sleep 5; done;"]
      volumeMounts:
      - name: secret-vol
        mountPath: "/secret"
        readOnly: true
    volumes:
    - name: secret-vol
      secret:
          secretName: mypassword
