apiVersion: v1
kind: Pod
metadata:
    name: clusterip-chk
spec:
    containers:
    - name: centos
      image: centos
      command: ["/bin/sh", "-c", "while : ;do curl http://nginx-svc:80/; sleep 5; done"]
