apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
    name: nginx-one-rs
spec:
    replicas: 2
    selector:
        matchLabels:
            project: gopro
            service: web
            version: "0.1"
    template:
        metadata:
            name: nginx
            labels:
                project: gopro
                service: web
                version: "0.1"
        spec:
            containers:
            - name: nginx
              image: nginx:1.12.0
              ports:
              - containerPort: 80
