apiVersion: v1
kind: Service
metadata:
    name: nginx-nodeport
spec:
    type: NodePort
    selector:
        project: gopro
        service: web
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
