apiVersion: v1
kind: Pod
metadata:
    name: netshare-pod
spec:
    containers:
    - name: nginx
      image: nginx
    - name: centos
      image: centos
      command: ["/bin/sh", "-c", "while true; do curl http://localhost:80/; sleep 10; done"]
