apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hue-learn-deployment
    namespace: hue
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: hue
                runtime-environment: production
                tier: backend-internal-service
            annotations:
                version: "4.0"
        spec:
            containers:
            - name: hue-learner
              image: g1g1/hue-learn:v4.0
              resources:
                  requests:
                      cpu: 200m
                      memory: 256Mi
              env:
              - name: DISCOVER_QUEUE
                value: dns
              - name: DISCOVER_STORE
                value: dns
