apiVersion: v1
kind: Pod
metadata:
    name: hue-learner
    labels:
        app: hue
        runtime-environment: production
        tier: backend-internal-service
    annotations:
        version: "3.0"
spec:
    containers:
    - name: hue-learner
      image: g1g1/hue-learn:v3.0
      resources:
          requests:
              cpu: 200m
              memory: 256Mi
      env:
      - name: DISCOVER_QUEUE
        value: dns
      - name: DISCOVER_STORE
        value: dns

