apiVersion: v1
kind: Pod
metadata:
    name: self-created-pod
    labels:
        project: nginx
        service: web
        version: "0.1"
spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80

