apiVersion: v1
kind: Pod
metadata:
    name: pod-with-secret
spec:
    containers:
    - name: hush
      image: redis
      volumeMounts:
      - name: secret-volume
        mountPath: "/mnt/secret-volume"
        readOnly: true
    volumes:
    - name: secret-volume
      secret:
          secretName: hush-secret
